# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6-stretch 

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4


    steps:
      - checkout
      - run:
          name: Install dependencies and set PATH
          command: |
              # Need gsl-dev for msprime. When we move to tskit we should 
              # be able to remove this.
              sudo apt-get install libcap-dev libnuma-dev libgsl-dev
              # way to set path persistently https://circleci.com/docs/2.0/env-vars/#setting-path
              echo 'export PATH=/home/circleci/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: Install tskit dev version
          command: |
              git clone https://github.com/tskit-dev/tskit.git ~/tskit || cd ~/tskit
      - run:
          name: Compile Python
          command: |
              python setup.py build_ext --inplace      
      - run:
          name: install dependencies
          command: |
              pip install -r requirements.txt --user
      - run:
          name: Install tskit dev version
          command: |
              python3 -m pip install git+https://github.com/tskit-dev/tskit.git#subdirectory=python --user
      - run:
          name: Lint Python
          command: |
              flake8 --max-line-length 89 tsinfer setup.py tests evaluation.py

      - run:
          name: Run Python tests
          command: |
              nosetests --with-coverage
              python3 -m codecov 
